# Generated by Django 4.1.4 on 2023-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(max_length=200)),
                ('km_driven', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
