# Generated by Django 4.1.4 on 2023-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehiclemodels_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodels',
            name='Image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
